{
  "openapi" : "3.1.0",
  "info" : {
    "title" : "CliqIntegJsonMapping",
    "version" : "1.0.0",
    "x-clan-group" : "integration",
    "x-module-group" : "integration"
  },
  "paths" : {
    "/api/v1/cliq/channels" : {
      "get" : {
        "tags" : [ "CliqIntegJsonMapping" ],
        "summary" : "Get cliq public channels list",
        "description" : "This api provides the list of public channels",
        "operationId" : "getChannelsList",
        "parameters" : [ {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/channelJsonResponse"
          },
          "400" : {
            "$ref" : "../common/Common.json#/components/responses/badRequestErrorResponse"
          },
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "cookie-auth" : [ "cookie-auth" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 20,
                  "hip" : false
                }, {
                  "duration" : 3600000,
                  "lock-period" : 600000,
                  "threshold" : 30,
                  "hip" : false
                }, {
                  "duration" : 86400000,
                  "lock-period" : 3000000,
                  "threshold" : 50,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "integration",
          "apihash" : "4310c834742015151cb6ad01d8827965",
          "module-group" : "integration",
          "apimethod" : "com.zoho.support.restapi.CliqService.getChannelsList"
        }
      },
      "post" : {
        "tags" : [ "CliqIntegJsonMapping" ],
        "summary" : "Create a cliq channel",
        "description" : "To create cliq channel from desk",
        "operationId" : "createChannel",
        "parameters" : [ {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/channelCreateJson"
        },
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/createChannelResponse"
          },
          "400" : {
            "$ref" : "../common/Common.json#/components/responses/badRequestErrorResponse"
          },
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/invalidDataErrorResponse"
          },
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "cookie-auth" : [ "cookie-auth" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 20,
                  "hip" : false
                }, {
                  "duration" : 3600000,
                  "lock-period" : 600000,
                  "threshold" : 30,
                  "hip" : false
                }, {
                  "duration" : 86400000,
                  "lock-period" : 3000000,
                  "threshold" : 50,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "integration",
          "apihash" : "70a746b4121a6406973512a6c502984f",
          "module-group" : "integration",
          "apimethod" : "com.zoho.support.restapi.CliqService.createCliqChannel"
        }
      }
    },
    "/api/v1/cliq/configuration" : {
      "get" : {
        "tags" : [ "CliqIntegJsonMapping" ],
        "summary" : "Get cliq configuration details",
        "description" : "This api provides details about cliq configuration",
        "operationId" : "getConfiguration",
        "parameters" : [ {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/configJsonResponse"
          },
          "400" : {
            "$ref" : "../common/Common.json#/components/responses/badRequestErrorResponse"
          },
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          },
          "204" : {
            "$ref" : "../common/Common.json#/components/responses/emptyResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "cookie-auth" : [ "cookie-auth" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 20,
                  "hip" : false
                }, {
                  "duration" : 3600000,
                  "lock-period" : 600000,
                  "threshold" : 30,
                  "hip" : false
                }, {
                  "duration" : 86400000,
                  "lock-period" : 3000000,
                  "threshold" : 50,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "integration",
          "apihash" : "71c5900dd48e71b77ec12d304c6d4fb9",
          "module-group" : "integration",
          "apimethod" : "com.zoho.support.restapi.CliqService.getCliqConfiguration"
        }
      },
      "post" : {
        "tags" : [ "CliqIntegJsonMapping" ],
        "summary" : "Create desk cliq integration",
        "description" : "This api integrates desk with cliq",
        "operationId" : "createIntegration",
        "parameters" : [ {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/IntegUpdateJson"
        },
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/configJsonResponse"
          },
          "400" : {
            "$ref" : "../common/Common.json#/components/responses/badRequestErrorResponse"
          },
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/multipleUnprocessEntityResponse"
          },
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          },
          "204" : {
            "$ref" : "../common/Common.json#/components/responses/emptyResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "cookie-auth" : [ "cookie-auth" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 20,
                  "hip" : false
                }, {
                  "duration" : 3600000,
                  "lock-period" : 600000,
                  "threshold" : 30,
                  "hip" : false
                }, {
                  "duration" : 86400000,
                  "lock-period" : 3000000,
                  "threshold" : 50,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "integration",
          "apihash" : "90840e1eff84be869d7e585e94500894",
          "module-group" : "integration",
          "apimethod" : "com.zoho.support.restapi.CliqService.createCliqIntegration"
        }
      },
      "delete" : {
        "tags" : [ "CliqIntegJsonMapping" ],
        "summary" : "Remove cliq integration",
        "description" : "This api removes the desk-cliq integration",
        "operationId" : "deleteIntegration",
        "parameters" : [ {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "../common/Common.json#/components/responses/emptyResponse"
          },
          "400" : {
            "$ref" : "../common/Common.json#/components/responses/badRequestErrorResponse"
          },
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "cookie-auth" : [ "cookie-auth" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 20,
                  "hip" : false
                }, {
                  "duration" : 3600000,
                  "lock-period" : 600000,
                  "threshold" : 30,
                  "hip" : false
                }, {
                  "duration" : 86400000,
                  "lock-period" : 3000000,
                  "threshold" : 50,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "integration",
          "apihash" : "9da2088f106a74fe9b2a33b04827ad50",
          "module-group" : "integration",
          "apimethod" : "com.zoho.support.restapi.CliqService.removeCliqIntegration"
        }
      },
      "patch" : {
        "tags" : [ "CliqIntegJsonMapping" ],
        "summary" : "Update cliq integration configuration",
        "description" : "This api updates the cliq integration details",
        "operationId" : "updateIntegration",
        "parameters" : [ {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/updateIntegration_IntegUpdateJson"
        },
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/configJsonResponse"
          },
          "400" : {
            "$ref" : "../common/Common.json#/components/responses/badRequestErrorResponse"
          },
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "cookie-auth" : [ "cookie-auth" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 20,
                  "hip" : false
                }, {
                  "duration" : 3600000,
                  "lock-period" : 600000,
                  "threshold" : 30,
                  "hip" : false
                }, {
                  "duration" : 86400000,
                  "lock-period" : 3000000,
                  "threshold" : 50,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "integration",
          "apihash" : "67e7e999cd5dbcea3fb0bc5d0e267341",
          "module-group" : "integration",
          "apimethod" : "com.zoho.support.restapi.CliqService.updateCliqConfiguration"
        }
      }
    },
    "/api/v1/cliq/notify" : {
      "post" : {
        "tags" : [ "CliqIntegJsonMapping" ],
        "summary" : "Send mail of conflict users",
        "description" : "Cliq can't be integrated if any of the agent in the desk organization are associated with multiple desk portals.This api sends mail of such conflict users",
        "operationId" : "sendMailForConflictUser",
        "parameters" : [ {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "400" : {
            "$ref" : "../common/Common.json#/components/responses/badRequestErrorResponse"
          },
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          },
          "204" : {
            "$ref" : "../common/Common.json#/components/responses/emptyResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "cookie-auth" : [ "cookie-auth" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 20,
                  "hip" : false
                }, {
                  "duration" : 3600000,
                  "lock-period" : 600000,
                  "threshold" : 30,
                  "hip" : false
                }, {
                  "duration" : 86400000,
                  "lock-period" : 3000000,
                  "threshold" : 50,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "integration",
          "apihash" : "c4d28e541f99648d8a21fab3ad8d3a40",
          "module-group" : "integration",
          "apimethod" : "com.zoho.support.restapi.CliqService.sendMailForConflictUsers"
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "channelFieldJson" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "uniqueName" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "level" : {
            "type" : [ "string", "null" ],
            "enum" : [ "organization", "private" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "image_url" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "name" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0,
            "x-custom-parameters-attributes" : {
              "removeExif" : false,
              "replacementString" : "",
              "filterMatchedContent" : false,
              "antivirus" : false,
              "allowInvalid" : false,
              "descrption" : "The channels will be retrieved based on the name provided",
              "secret" : false,
              "preserveCharsLimit" : 10,
              "trim" : false,
              "internalParam" : false,
              "preserveChars" : "0,5",
              "importUrl" : false,
              "decrypt" : false
            }
          },
          "id" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "status" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          }
        },
        "required" : [ "id", "image_url", "level", "name", "status", "uniqueName" ]
      },
      "channelJsonArray" : {
        "type" : [ "null", "array" ],
        "items" : {
          "$ref" : "./CliqIntegJsonMapping.json#/components/schemas/channelFieldJson"
        }
      },
      "departmentChannelMappingJson" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "departmentId" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "channelId" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "status" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          }
        },
        "required" : [ "channelId", "departmentId", "status" ]
      },
      "departmentChannelMappingJsonArray" : {
        "type" : [ "null", "array" ],
        "items" : {
          "$ref" : "./CliqIntegJsonMapping.json#/components/schemas/departmentChannelMappingJson"
        }
      },
      "notifyOnceJson" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "ticketCommentAdded" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "ticketStatusUpdatedTo" : {
            "type" : [ "null", "array" ],
            "items" : {
              "type" : [ "string", "null" ],
              "maxLength" : 100,
              "minLength" : 0
            },
            "uniqueItems" : false
          },
          "customerFeedbackReceived" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "callCreated" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "taskReminder" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "callCompleted" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "ticketClosed" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "ticketMoved" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "eventCompleted" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "ticketCommentMentions" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "ticketCreated" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "ticketResolution" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "ticketReopened" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "taskCreated" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "ticketBlueprintUpdated" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "taskCompleted" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "callReminder" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "eventReminder" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "ticketAssigneeChanged" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "ticketEscalated" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          },
          "eventCreated" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          }
        },
        "required" : [ "callCompleted", "callCreated", "callReminder", "customerFeedbackReceived", "eventCompleted", "eventCreated", "eventReminder", "taskCompleted", "taskCreated", "taskReminder", "ticketAssigneeChanged", "ticketBlueprintUpdated", "ticketClosed", "ticketCommentAdded", "ticketCommentMentions", "ticketCreated", "ticketEscalated", "ticketMoved", "ticketReopened", "ticketResolution", "ticketStatusUpdatedTo" ]
      },
      "notificationPreferenceJson" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "notifyOnce" : {
            "$ref" : "#/components/schemas/notifyOnceJson"
          },
          "isAgentDirectMessageEnabled" : {
            "type" : [ "string", "null" ],
            "enum" : [ "true", "false" ]
          }
        },
        "required" : [ "isAgentDirectMessageEnabled", "notifyOnce" ]
      },
      "defaultChannelJson" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "uniqueName" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "id" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          }
        },
        "required" : [ "id", "uniqueName" ]
      }
    },
    "responses" : {
      "channelJsonResponse" : {
        "description" : "channelJsonResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "channels" : {
                  "$ref" : "./CliqIntegJsonMapping.json#/components/schemas/channelJsonArray"
                },
                "has_more" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0
                },
                "next_token" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 300,
                  "minLength" : 0,
                  "x-custom-parameters-attributes" : {
                    "removeExif" : false,
                    "replacementString" : "",
                    "filterMatchedContent" : false,
                    "antivirus" : false,
                    "allowInvalid" : false,
                    "descrption" : "A pointer from which the channels will be fetched",
                    "secret" : false,
                    "preserveCharsLimit" : 10,
                    "trim" : false,
                    "internalParam" : false,
                    "preserveChars" : "0,5",
                    "importUrl" : false,
                    "decrypt" : false
                  }
                }
              },
              "required" : [ "channels", "has_more", "next_token" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "channels" : [ {
                    "uniqueName" : "desk integration",
                    "level" : "organization",
                    "image_url" : "http://cliq.zoho.com/channel/T4000000040005_41312792_1498572169593/photo.do",
                    "name" : "#desk integration",
                    "id" : "O1345000000004009",
                    "status" : "pending"
                  }, {
                    "uniqueName" : "desk integration",
                    "level" : "team",
                    "image_url" : "http://cliq.zoho.com/channel/T4000000040005_415342792_1498572169593/photo.do",
                    "name" : "#cliq integration",
                    "id" : "O1324192310004009",
                    "status" : "created"
                  } ],
                  "has_more" : "false",
                  "next_token" : "bdfeecaf65c8942ed874151cd588ec0e21e4c26a5ef21771fc7c67640fa55e793c0ddee855083bbe3dffa4596c6cdb0673d4d43bb8ba77964ee8885b63cdc392"
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "configJsonResponse" : {
        "description" : "configJsonResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "latestVersion" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0
                },
                "notificationPreference" : {
                  "$ref" : "#/components/schemas/notificationPreferenceJson"
                },
                "notifyVia" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0,
                  "x-custom-parameters-attributes" : {
                    "removeExif" : false,
                    "replacementString" : "",
                    "filterMatchedContent" : false,
                    "antivirus" : false,
                    "allowInvalid" : false,
                    "descrption" : "This enables you to choose the mode via which the notifications should get pushed to cliq.Allowed values are defaultChannel and customMapping",
                    "secret" : false,
                    "preserveCharsLimit" : 10,
                    "trim" : false,
                    "internalParam" : false,
                    "preserveChars" : "0,5",
                    "importUrl" : false,
                    "decrypt" : false
                  }
                },
                "installedVersion" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0,
                  "x-custom-parameters-attributes" : {
                    "removeExif" : false,
                    "replacementString" : "",
                    "filterMatchedContent" : false,
                    "antivirus" : false,
                    "allowInvalid" : false,
                    "descrption" : "Version of cliq to be integrated",
                    "secret" : false,
                    "preserveCharsLimit" : 10,
                    "trim" : false,
                    "internalParam" : false,
                    "preserveChars" : "0,5",
                    "importUrl" : false,
                    "decrypt" : false
                  }
                },
                "departmentChannelMapping" : {
                  "$ref" : "./CliqIntegJsonMapping.json#/components/schemas/departmentChannelMappingJsonArray"
                },
                "defaultChannel" : {
                  "$ref" : "./CliqIntegJsonMapping.json#/components/schemas/defaultChannelJson"
                },
                "status" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0,
                  "x-custom-parameters-attributes" : {
                    "removeExif" : false,
                    "replacementString" : "",
                    "filterMatchedContent" : false,
                    "antivirus" : false,
                    "allowInvalid" : false,
                    "descrption" : "Status of cliq integration, It can be either enabled or disabled",
                    "secret" : false,
                    "preserveCharsLimit" : 10,
                    "trim" : false,
                    "internalParam" : false,
                    "preserveChars" : "0,5",
                    "importUrl" : false,
                    "decrypt" : false
                  }
                }
              },
              "required" : [ "defaultChannel", "departmentChannelMapping", "installedVersion", "latestVersion", "notificationPreference", "notifyVia", "status" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "notificationPreference" : {
                    "notifyOnce" : {
                      "ticketCommentAdded" : "true",
                      "ticketStatusUpdatedTo" : [ "Open", "InProgress", "Closed" ],
                      "customerFeedbackReceived" : "true",
                      "callCreated" : "true",
                      "taskReminder" : "true",
                      "callCompleted" : "true",
                      "ticketClosed" : "false",
                      "ticketMoved" : "false",
                      "eventCompleted" : "true",
                      "ticketCommentMentions" : "true",
                      "ticketCreated" : "true",
                      "ticketResolution" : "true",
                      "ticketReopened" : "false",
                      "taskCreated" : "true",
                      "ticketBlueprintUpdated" : "true",
                      "taskCompleted" : "true",
                      "callReminder" : "true",
                      "eventReminder" : "true",
                      "ticketAssigneeChanged" : "true",
                      "ticketEscalated" : "true",
                      "eventCreated" : "true"
                    },
                    "isAgentDirectMessageEnabled" : "true"
                  },
                  "notifyVia" : "defaultChannel",
                  "installedVersion" : "1.0",
                  "departmentChannelMapping" : [ {
                    "departmentId" : "63148054672682313",
                    "channelId" : "78912000000261323",
                    "status" : "enabled"
                  }, {
                    "departmentId" : "63148129000278893",
                    "channelId" : "98123000000269873",
                    "status" : "enabled"
                  } ],
                  "defaultChannel" : {
                    "uniqueName" : "Desk Support",
                    "id" : "98123000000269873"
                  },
                  "status" : "enabled"
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "createChannelResponse" : {
        "description" : "createChannelResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "uniqueName" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0
                },
                "level" : {
                  "type" : [ "string", "null" ],
                  "enum" : [ "organization", "private" ],
                  "maxLength" : 100,
                  "minLength" : 0,
                  "x-custom-parameters-attributes" : {
                    "removeExif" : false,
                    "replacementString" : "",
                    "filterMatchedContent" : false,
                    "antivirus" : false,
                    "allowInvalid" : false,
                    "descrption" : "Level of the channel",
                    "secret" : false,
                    "preserveCharsLimit" : 10,
                    "trim" : false,
                    "internalParam" : false,
                    "preserveChars" : "0,5",
                    "importUrl" : false,
                    "decrypt" : false
                  }
                },
                "image_url" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0
                },
                "name" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0,
                  "x-custom-parameters-attributes" : {
                    "removeExif" : false,
                    "replacementString" : "",
                    "filterMatchedContent" : false,
                    "antivirus" : false,
                    "allowInvalid" : false,
                    "descrption" : "Name of the channel",
                    "secret" : false,
                    "preserveCharsLimit" : 10,
                    "trim" : false,
                    "internalParam" : false,
                    "preserveChars" : "0,5",
                    "importUrl" : false,
                    "decrypt" : false
                  }
                },
                "id" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0
                }
              },
              "required" : [ "id", "image_url", "level", "name", "uniqueName" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "uniqueName" : "desk integration",
                  "level" : "organization",
                  "image_url" : "http://cliq.zoho.com/channel/T4000000040005_415342792_1498572169593/photo.do",
                  "name" : "#desk integration",
                  "id" : "O1345000000004009"
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      }
    },
    "parameters" : { },
    "requestBodies" : {
      "IntegUpdateJson" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "status" : {
                  "type" : [ "string", "null" ],
                  "description" : "Status of cliq integration, It can be either enabled or disabled",
                  "enum" : [ "enabled", "disabled" ],
                  "maxLength" : 100,
                  "minLength" : 0
                }
              },
              "required" : [ "status" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "status" : "enabled"
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      },
      "channelCreateJson" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "level" : {
                  "type" : [ "string", "null" ],
                  "description" : "Level of the channel",
                  "enum" : [ "organization", "private" ],
                  "maxLength" : 100,
                  "minLength" : 0
                },
                "name" : {
                  "type" : [ "string", "null" ],
                  "description" : "Name of the channel",
                  "maxLength" : 100,
                  "minLength" : 0
                }
              },
              "required" : [ "level", "name" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "level" : "team",
                  "name" : "Desk Integration Channel"
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      },
      "updateIntegration_IntegUpdateJson" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "status" : {
                  "type" : [ "string", "null" ],
                  "description" : "Status of cliq integration, It can be either enabled or disabled",
                  "enum" : [ "enabled", "disabled" ],
                  "maxLength" : 100,
                  "minLength" : 0
                }
              }
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "status" : "enabled"
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      }
    },
    "securitySchemes" : {
      "cookie-auth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/cookie-auth"
      },
      "org-oauth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/org-oauth"
      },
      "jwt-oauth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/jwt-oauth"
      },
      "iam-oauth2-schema" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/iam-oauth2-schema"
      }
    }
  },
  "x-entity" : "CliqIntegJsonMapping"
}