{
  "openapi" : "3.1.0",
  "info" : {
    "title" : "Label",
    "version" : "1.0.0",
    "x-clan-group" : "helpCenter",
    "x-module-group" : "solutions"
  },
  "paths" : {
    "/api/v1/labels/{labelId}/users" : {
      "get" : {
        "tags" : [ "Label" ],
        "summary" : "List users under a label",
        "description" : "This API lists a particular number of users under a label, based on the limit defined.",
        "operationId" : "getUsersByLabel",
        "parameters" : [ {
          "$ref" : "#/components/parameters/limit"
        }, {
          "$ref" : "#/components/parameters/searchBy"
        }, {
          "$ref" : "#/components/parameters/from"
        }, {
          "name" : "sortBy",
          "in" : "query",
          "description" : "Key that sorts the list of users by a specific attribute: -(@assignedTime@)",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string", "null" ],
            "description" : "Key that sorts the list of users by a specific attribute: -(@assignedTime@)",
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "-?(assignedTime)"
          }
        }, {
          "$ref" : "#/components/parameters/labelId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "404" : {
            "$ref" : "../common/Common.json#/components/responses/urlNotFoundErrorResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/userLabelListResponse"
          },
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/invalidDataErrorResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.contacts.READ", "Desk.settings.READ", "Desk.search.READ" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 80,
                  "hip" : false
                }, {
                  "duration" : 3600000,
                  "lock-period" : 1200000,
                  "threshold" : 800,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : {
              "deprecatedScopes" : [ "settings" ]
            }
          },
          "clan-group" : "helpCenter",
          "apihash" : "a23176b7832bb60312d5c40a78cfe03a",
          "module-group" : "solutions",
          "apimethod" : "com.zoho.desk.helpcenter.label.rest.support.LabelService.getUsersUnderLabel"
        }
      }
    },
    "/api/v1/labels" : {
      "get" : {
        "tags" : [ "Label" ],
        "summary" : "List labels",
        "description" : "This API lists a particular number of labels, based on the limit defined. ",
        "operationId" : "getLabels",
        "parameters" : [ {
          "$ref" : "#/components/parameters/limit"
        }, {
          "$ref" : "#/components/parameters/searchBy"
        }, {
          "$ref" : "#/components/parameters/from"
        }, {
          "name" : "sortBy",
          "in" : "query",
          "description" : "Key that sorts the list of labels by a particular attribute: -(@createdTime@ or @modifiedTime@, or @name@)",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string", "null" ],
            "description" : "Key that sorts the list of labels by a particular attribute: -(@createdTime@ or @modifiedTime@, or @name@)",
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "-?(createdTime|modifiedTime|name)"
          }
        }, {
          "name" : "helpCenterId",
          "in" : "query",
          "description" : "ID of the help center from which the labels must be fetched",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "description" : "ID of the help center from which the labels must be fetched",
            "pattern" : "([0-9]+)"
          }
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/invalidDataErrorResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/labelListViewResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.contacts.READ", "Desk.settings.READ" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 25,
                  "hip" : false
                }, {
                  "duration" : 3600000,
                  "lock-period" : 600000,
                  "threshold" : 100,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : {
              "deprecatedScopes" : [ "settings" ]
            }
          },
          "clan-group" : "helpCenter",
          "apihash" : "75af88e220233aef1a3a81f44a1b3fc8",
          "module-group" : "solutions",
          "apimethod" : "com.zoho.desk.helpcenter.label.rest.support.LabelService.getLabels"
        }
      },
      "post" : {
        "tags" : [ "Label" ],
        "summary" : "Create label",
        "description" : "This API creates a label in your help center.",
        "operationId" : "createLabel",
        "parameters" : [ {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/createLabelPayloadJson"
        },
        "responses" : {
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/invalidDataErrorResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/labelDetailViewResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.contacts.CREATE", "Desk.settings.CREATE" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 20,
                  "hip" : false
                }, {
                  "duration" : 3600000,
                  "lock-period" : 1200000,
                  "threshold" : 100,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : {
              "deprecatedScopes" : [ "settings" ]
            }
          },
          "clan-group" : "helpCenter",
          "apihash" : "e5f2a398029febd6736ef9a9445cb9eb",
          "module-group" : "solutions",
          "apimethod" : "com.zoho.desk.helpcenter.label.rest.support.LabelService.addLabel"
        }
      }
    },
    "/api/v1/labels/{labelId}" : {
      "get" : {
        "tags" : [ "Label" ],
        "summary" : "Get details of label",
        "description" : "This API fetches the details of a particular label.",
        "operationId" : "getLabel",
        "parameters" : [ {
          "$ref" : "#/components/parameters/labelId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "404" : {
            "$ref" : "../common/Common.json#/components/responses/urlNotFoundErrorResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/labelDetailViewResponse"
          },
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/invalidDataErrorResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.contacts.READ", "Desk.settings.READ" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "policy" : "ReadAPI_Standard_UserPolicy"
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : {
              "deprecatedScopes" : [ "settings" ]
            }
          },
          "clan-group" : "helpCenter",
          "apihash" : "270d581e6d0ea7958e0c48813e00de85",
          "module-group" : "solutions",
          "apimethod" : "com.zoho.desk.helpcenter.label.rest.support.LabelService.getLabel"
        }
      },
      "delete" : {
        "tags" : [ "Label" ],
        "summary" : "Delete label",
        "description" : "This API deletes a label from your help center.",
        "operationId" : "deleteLabel",
        "parameters" : [ {
          "$ref" : "#/components/parameters/labelId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/invalidDataErrorResponse"
          },
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          },
          "204" : {
            "$ref" : "../common/Common.json#/components/responses/emptyResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.contacts.DELETE", "Desk.settings.DELETE" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 20,
                  "hip" : false
                }, {
                  "duration" : 3600000,
                  "lock-period" : 600000,
                  "threshold" : 100,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : {
              "deprecatedScopes" : [ "settings" ]
            }
          },
          "clan-group" : "helpCenter",
          "apihash" : "2e80dcf0d40ffc0176cbd1de3e91e572",
          "module-group" : "solutions",
          "apimethod" : "com.zoho.desk.helpcenter.label.rest.support.LabelService.deleteLabel"
        }
      },
      "patch" : {
        "tags" : [ "Label" ],
        "summary" : "Update label",
        "description" : "This API helps update the details of a label.",
        "operationId" : "updateLabel",
        "parameters" : [ {
          "$ref" : "#/components/parameters/labelId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/updateLabelPayloadJSON"
        },
        "responses" : {
          "404" : {
            "$ref" : "../common/Common.json#/components/responses/urlNotFoundErrorResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/labelDetailViewResponse"
          },
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/invalidDataErrorResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.contacts.UPDATE", "Desk.settings.UPDATE" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 10,
                  "hip" : false
                }, {
                  "duration" : 3600000,
                  "lock-period" : 1200000,
                  "threshold" : 100,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : {
              "deprecatedScopes" : [ "settings" ]
            }
          },
          "clan-group" : "helpCenter",
          "apihash" : "b623785fa8f90a38c2db280dda35e291",
          "module-group" : "solutions",
          "apimethod" : "com.zoho.desk.helpcenter.label.rest.support.LabelService.updateLabel"
        }
      }
    },
    "/api/v1/labels/{labelId}/users/add" : {
      "post" : {
        "tags" : [ "Label" ],
        "summary" : "Assign label to users",
        "description" : "This API assigns a particular label to multiple users.",
        "operationId" : "assignLabelToUsers",
        "parameters" : [ {
          "$ref" : "#/components/parameters/labelId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/userIdsPayLoad"
        },
        "responses" : {
          "404" : {
            "$ref" : "../common/Common.json#/components/responses/urlNotFoundErrorResponse"
          },
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/invalidDataErrorResponse"
          },
          "204" : {
            "$ref" : "../common/Common.json#/components/responses/emptyResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.contacts.UPDATE", "Desk.settings.UPDATE" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 20,
                  "hip" : false
                }, {
                  "duration" : 3600000,
                  "lock-period" : 600000,
                  "threshold" : 200,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : {
              "deprecatedScopes" : [ "settings" ]
            }
          },
          "clan-group" : "helpCenter",
          "apihash" : "2c3641c8055aebdb9c006303e66460e3",
          "module-group" : "solutions",
          "apimethod" : "com.zoho.desk.helpcenter.label.rest.support.LabelService.assignLabelToUsers"
        }
      }
    },
    "/api/v1/labels/{labelId}/users/remove" : {
      "post" : {
        "tags" : [ "Label" ],
        "summary" : "Remove users under a label",
        "description" : "This API removes all users under a particular label. ",
        "operationId" : "removeLabelsFromUsers",
        "parameters" : [ {
          "$ref" : "#/components/parameters/labelId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/removeLabelsFromUsers_userIdsPayLoad"
        },
        "responses" : {
          "404" : {
            "$ref" : "../common/Common.json#/components/responses/urlNotFoundErrorResponse"
          },
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/invalidDataErrorResponse"
          },
          "204" : {
            "$ref" : "../common/Common.json#/components/responses/emptyResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.contacts.UPDATE", "Desk.settings.UPDATE" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 20,
                  "hip" : false
                }, {
                  "duration" : 3600000,
                  "lock-period" : 600000,
                  "threshold" : 200,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : {
              "deprecatedScopes" : [ "settings" ]
            }
          },
          "clan-group" : "helpCenter",
          "apihash" : "ca6e988fbaf62da2f411cacc7135c116",
          "module-group" : "solutions",
          "apimethod" : "com.zoho.desk.helpcenter.label.rest.support.LabelService.removeLabelsFromUsers"
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "labelPreferenceResponse" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "bgColor" : {
            "type" : [ "string", "null" ],
            "description" : "background color of the label",
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "^#?(([a-fA-F0-9]){3}){1,2}$"
          },
          "shape" : {
            "type" : [ "string", "null" ],
            "description" : "shape of the label",
            "enum" : [ "ROUNDED", "RECTANGLE" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "textColor" : {
            "type" : [ "string", "null" ],
            "description" : "text color of the label",
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "^#?(([a-fA-F0-9]){3}){1,2}$"
          }
        },
        "required" : [ "bgColor", "shape", "textColor" ]
      },
      "labelMetaResponse" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "preferences" : {
            "$ref" : "./Label.json#/components/schemas/labelPreferenceResponse"
          },
          "name" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "[0-9a-zA-Z_\\-\\&\\.\\$\\@\\^\\(\\)\\{\\}\\~\\=\\-\\|\\*\\+\\?\\[\\]\\,\\:\\'\\/\\!\\P{InBasicLatin}\\s]+"
          },
          "id" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "logoUrl" : {
            "type" : [ "string", "null" ],
            "maxLength" : 200,
            "minLength" : 0,
            "pattern" : "(^(ht|f)tp(s?)\\://[-.\\w]*(/?)([a-zA-Z0-9\\-\\.\\?\\,\\:\\'/\\\\+=&amp;%\\$#_@]*)?$)"
          }
        },
        "required" : [ "id", "logoUrl", "name", "preferences" ]
      },
      "creatorResponse" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "photoUrl" : {
            "type" : [ "string", "null" ],
            "maxLength" : 200,
            "minLength" : 0,
            "pattern" : "(^(ht|f)tp(s?)\\://[-.\\w]*(/?)([a-zA-Z0-9\\-\\.\\?\\,\\:\\'/\\\\+=&amp;%\\$#_@]*)?$)"
          },
          "name" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "id" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        },
        "required" : [ "id", "name", "photoUrl" ]
      },
      "userLabelResponse" : {
        "additionalProperties" : false,
        "allOf" : [ {
          "$ref" : "./User.json#/components/schemas/userMetaJson"
        }, {
          "type" : [ "null", "object" ],
          "properties" : {
            "assignee" : {
              "$ref" : "./Label.json#/components/schemas/creatorResponse"
            },
            "assignedTime" : {
              "type" : [ "string", "null" ],
              "maxLength" : 100,
              "minLength" : 0,
              "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
            }
          },
          "required" : [ "assignedTime", "assignee" ]
        } ]
      },
      "userLabelData" : {
        "type" : [ "null", "array" ],
        "items" : {
          "$ref" : "./Label.json#/components/schemas/userLabelResponse"
        }
      },
      "updateLabelPayloadJSON" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "preferences" : {
            "$ref" : "./Label.json#/components/schemas/labelPreferenceResponse"
          },
          "name" : {
            "type" : [ "string", "null" ],
            "description" : "Name of the label",
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "[0-9a-zA-Z_\\-\\&\\.\\$\\@\\^\\(\\)\\{\\}\\~\\=\\-\\|\\*\\+\\?\\[\\]\\,\\:\\'\\/\\!\\P{InBasicLatin}\\s]+"
          },
          "logoId" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "description" : "ID of the logo set for the label",
            "pattern" : "([0-9]+)"
          }
        },
        "required" : [ "logoId", "name", "preferences" ]
      },
      "labelDetailViewResponse" : {
        "additionalProperties" : false,
        "allOf" : [ {
          "$ref" : "./Label.json#/components/schemas/labelMetaResponse"
        }, {
          "type" : [ "null", "object" ],
          "properties" : {
            "modifiedTime" : {
              "type" : [ "string", "null" ],
              "maxLength" : 100,
              "minLength" : 0,
              "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
            },
            "creator" : {
              "$ref" : "./Label.json#/components/schemas/creatorResponse"
            },
            "modifier" : {
              "$ref" : "./Label.json#/components/schemas/creatorResponse"
            },
            "count" : {
              "type" : [ "string", "null", "integer" ],
              "format" : "int32",
              "pattern" : "([0-9]+)"
            },
            "createdTime" : {
              "type" : [ "string", "null" ],
              "maxLength" : 100,
              "minLength" : 0,
              "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
            },
            "helpCenterId" : {
              "type" : [ "string", "null", "integer" ],
              "format" : "int64",
              "pattern" : "([0-9]+)",
              "x-custom-parameters-attributes" : {
                "removeExif" : false,
                "filterMatchedContent" : false,
                "antivirus" : false,
                "replacementString" : "",
                "allowInvalid" : false,
                "descrption" : "ID of the help center from which the labels must be fetched",
                "secret" : false,
                "preserveCharsLimit" : 10,
                "trim" : false,
                "internalParam" : false,
                "preserveChars" : "0,5",
                "importUrl" : false,
                "decrypt" : false
              }
            }
          },
          "required" : [ "count", "createdTime", "creator", "helpCenterId", "modifiedTime", "modifier" ]
        } ]
      },
      "labelData" : {
        "type" : [ "null", "array" ],
        "items" : {
          "$ref" : "./Label.json#/components/schemas/labelDetailViewResponse"
        }
      },
      "userLabelMetaResponse" : {
        "additionalProperties" : false,
        "allOf" : [ {
          "$ref" : "./Label.json#/components/schemas/labelMetaResponse"
        }, {
          "type" : [ "null", "object" ],
          "properties" : {
            "isPrimary" : {
              "type" : [ "boolean", "null" ],
              "x-custom-parameters-attributes" : {
                "removeExif" : false,
                "filterMatchedContent" : false,
                "antivirus" : false,
                "replacementString" : "",
                "allowInvalid" : false,
                "descrption" : "Key that filters the primary label assigned to the user",
                "secret" : false,
                "preserveCharsLimit" : 10,
                "trim" : false,
                "internalParam" : false,
                "preserveChars" : "0,5",
                "importUrl" : false,
                "decrypt" : false
              }
            },
            "helpCenterId" : {
              "type" : [ "string", "null", "integer" ],
              "format" : "int64",
              "pattern" : "([0-9]+)",
              "x-custom-parameters-attributes" : {
                "removeExif" : false,
                "filterMatchedContent" : false,
                "antivirus" : false,
                "replacementString" : "",
                "allowInvalid" : false,
                "descrption" : "ID of the help center from which the labels must be fetched",
                "secret" : false,
                "preserveCharsLimit" : 10,
                "trim" : false,
                "internalParam" : false,
                "preserveChars" : "0,5",
                "importUrl" : false,
                "decrypt" : false
              }
            },
            "assignedTime" : {
              "type" : [ "string", "null" ],
              "maxLength" : 100,
              "minLength" : 0,
              "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
            }
          },
          "required" : [ "assignedTime", "helpCenterId", "isPrimary" ]
        } ]
      },
      "labelIdsArr" : {
        "type" : [ "null", "array" ],
        "items" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int64",
          "pattern" : "([0-9]+)"
        }
      }
    },
    "responses" : {
      "userLabelListResponse" : {
        "description" : "userLabelListResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "data" : {
                  "$ref" : "./Label.json#/components/schemas/userLabelData"
                }
              },
              "required" : [ "data" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "data" : [ {
                    "photoUrl" : null,
                    "emailAddress" : "carol@zylker.com",
                    "name" : "svega RM",
                    "userType" : "ENDUSER",
                    "assignee" : {
                      "photoUrl" : "https://desk.zoho.com/portal/api/user/6000000015895/photo?orgId=143315",
                      "name" : "Chris",
                      "id" : "6000000015895"
                    },
                    "id" : "6000000032907",
                    "assignedTime" : 1565336864000,
                    "status" : "ACTIVE"
                  } ]
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "labelDetailViewResponse" : {
        "description" : "labelDetailViewResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "additionalProperties" : false,
              "allOf" : [ {
                "$ref" : "./Label.json#/components/schemas/labelMetaResponse"
              }, {
                "type" : [ "null", "object" ],
                "properties" : {
                  "modifiedTime" : {
                    "type" : [ "string", "null" ],
                    "maxLength" : 100,
                    "minLength" : 0,
                    "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
                  },
                  "creator" : {
                    "$ref" : "./Label.json#/components/schemas/creatorResponse"
                  },
                  "modifier" : {
                    "$ref" : "./Label.json#/components/schemas/creatorResponse"
                  },
                  "count" : {
                    "type" : [ "string", "null", "integer" ],
                    "format" : "int32",
                    "pattern" : "([0-9]+)"
                  },
                  "createdTime" : {
                    "type" : [ "string", "null" ],
                    "maxLength" : 100,
                    "minLength" : 0,
                    "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
                  },
                  "helpCenterId" : {
                    "type" : [ "string", "null", "integer" ],
                    "format" : "int64",
                    "pattern" : "([0-9]+)"
                  }
                },
                "required" : [ "count", "createdTime", "creator", "helpCenterId", "modifiedTime", "modifier" ]
              } ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "modifiedTime" : 1505797130000,
                  "preferences" : {
                    "shape" : "ROUNDED",
                    "bgColor" : "#FFEE",
                    "textColor" : "#FFEE"
                  },
                  "creator" : {
                    "photoURL" : "https://desk.zoho.com/portal/api/user/6000000015895/photo?orgId=143315",
                    "name" : "SupportAdmin",
                    "id" : "310975130121"
                  },
                  "modifier" : {
                    "photoURL" : "https://desk.zoho.com/portal/api/user/6000000015895/photo?orgId=143315",
                    "name" : "SupportAdmin",
                    "id" : "310975130121"
                  },
                  "name" : "Pro Customer",
                  "count" : "892",
                  "createdTime" : 1505797130000,
                  "id" : "310975130110",
                  "helpCenterId" : "310975130119",
                  "logoUrl" : "https://desk.zoho.com/portal/api/publicImages/310975130121?portalId=5c9470fcc808cc98932703e28221d6c302e105dc4da8b23fafb6719abeecaa48"
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "labelListViewResponse" : {
        "description" : "labelListViewResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "data" : {
                  "$ref" : "./Label.json#/components/schemas/labelData"
                }
              },
              "required" : [ "data" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "data" : [ {
                    "modifiedTime" : 1505797130000,
                    "preferences" : {
                      "shape" : "ROUNDED",
                      "bgColor" : "#FFEE",
                      "textColor" : "#FFEE"
                    },
                    "creator" : {
                      "photoURL" : "https://desk.zoho.com/portal/api/user/6000000015895/photo?orgId=143315",
                      "name" : "SupportAdmin",
                      "id" : "310975130121"
                    },
                    "modifier" : {
                      "photoURL" : "https://desk.zoho.com/portal/api/user/6000000015895/photo?orgId=143315",
                      "name" : "SupportAdmin",
                      "id" : "310975130121"
                    },
                    "name" : "Pro Customer",
                    "count" : "892",
                    "createdTime" : 1505797130000,
                    "id" : "310975130110",
                    "helpCenterId" : "310975130119",
                    "logoUrl" : "https://desk.zoho.com/portal/api/publicImages/310975130121?portalId=5c9470fcc808cc98932703e28221d6c302e105dc4da8b23fafb6719abeecaa48"
                  } ]
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      }
    },
    "parameters" : {
      "labelId" : {
        "name" : "labelId",
        "in" : "path",
        "required" : true,
        "style" : "simple",
        "explode" : false,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int64",
          "pattern" : "([0-9]+)"
        }
      },
      "limit" : {
        "name" : "limit",
        "in" : "query",
        "description" : "Number of users to list. The default value is 50 and the maximum value allowed is 100",
        "required" : false,
        "style" : "form",
        "explode" : true,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int32",
          "description" : "Number of users to list. The default value is 50 and the maximum value allowed is 100",
          "maximum" : 50,
          "minimum" : 1,
          "pattern" : "([0-9]+)"
        }
      },
      "searchBy" : {
        "name" : "searchBy",
        "in" : "query",
        "description" : "Search keyword to use for finding a particular user. The keyword must contain at least two characters.",
        "required" : false,
        "style" : "form",
        "explode" : true,
        "schema" : {
          "type" : [ "string", "null" ],
          "description" : "Search keyword to use for finding a particular user. The keyword must contain at least two characters.",
          "maxLength" : 100,
          "minLength" : 0
        }
      },
      "from" : {
        "name" : "from",
        "in" : "query",
        "description" : "Index number, starting from which the users must be fetched. The default value is 1. ",
        "required" : false,
        "style" : "form",
        "explode" : true,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int32",
          "description" : "Index number, starting from which the users must be fetched. The default value is 1. ",
          "minimum" : 1,
          "pattern" : "([0-9]+)"
        }
      }
    },
    "requestBodies" : {
      "createLabelPayloadJson" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "additionalProperties" : false,
              "allOf" : [ {
                "$ref" : "./Label.json#/components/schemas/updateLabelPayloadJSON"
              }, {
                "type" : [ "null", "object" ],
                "properties" : {
                  "helpCenterId" : {
                    "type" : [ "string", "null", "integer" ],
                    "format" : "int64",
                    "description" : "ID of the help center in which the label must be created",
                    "pattern" : "([0-9]+)"
                  }
                }
              }, {
                "type" : "object",
                "required" : [ "helpCenterId", "name" ]
              } ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "preferences" : {
                    "shape" : "ROUNDED",
                    "bgColor" : "#FFEE",
                    "textColor" : "#FFEE"
                  },
                  "name" : "Pro Customer",
                  "helpCenterId" : "310975130119",
                  "logoId" : "310975130121"
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      },
      "userIdsPayLoad" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "userIds" : {
                  "type" : [ "null", "array" ],
                  "items" : {
                    "type" : [ "string", "null", "integer" ],
                    "format" : "int64",
                    "pattern" : "([0-9]+)",
                    "x-custom-parameters-attributes" : [ { } ]
                  },
                  "uniqueItems" : false
                }
              },
              "required" : [ "userIds" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "userIds" : [ "3109751143253", "310975131231", "310975133141", "310975101849" ]
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      },
      "updateLabelPayloadJSON" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "preferences" : {
                  "$ref" : "./Label.json#/components/schemas/labelPreferenceResponse"
                },
                "name" : {
                  "type" : [ "string", "null" ],
                  "description" : "Name of the label",
                  "maxLength" : 100,
                  "minLength" : 0,
                  "pattern" : "[0-9a-zA-Z_\\-\\&\\.\\$\\@\\^\\(\\)\\{\\}\\~\\=\\-\\|\\*\\+\\?\\[\\]\\,\\:\\'\\/\\!\\P{InBasicLatin}\\s]+"
                },
                "logoId" : {
                  "type" : [ "string", "null", "integer" ],
                  "format" : "int64",
                  "description" : "ID of the logo set for the label",
                  "pattern" : "([0-9]+)"
                }
              }
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "preferences" : {
                    "shape" : "ROUNDED",
                    "bgColor" : "#FFEE",
                    "textColor" : "#FFEE"
                  },
                  "name" : "Pro Customer",
                  "logoId" : "310975130121"
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      },
      "removeLabelsFromUsers_userIdsPayLoad" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "userIds" : {
                  "type" : [ "null", "array" ],
                  "items" : {
                    "type" : [ "string", "null", "integer" ],
                    "format" : "int64",
                    "pattern" : "([0-9]+)",
                    "x-custom-parameters-attributes" : [ { } ]
                  },
                  "uniqueItems" : false
                }
              },
              "required" : [ "userIds" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "userIds" : [ "3109751143253", "310975131231", "310975133141", "310975101849" ]
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      },
      "labelIdsJson" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "labelIds" : {
                  "$ref" : "./Label.json#/components/schemas/labelIdsArr"
                }
              },
              "required" : [ "labelIds" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "labelIds" : [ "24073000002958023", "24073000002952323" ]
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      }
    },
    "securitySchemes" : {
      "cookie-auth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/cookie-auth"
      },
      "org-oauth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/org-oauth"
      },
      "iam-oauth2-schema" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/iam-oauth2-schema"
      }
    }
  },
  "x-entity" : "Label"
}