{
  "openapi" : "3.1.0",
  "info" : {
    "title" : "TicketTag",
    "version" : "1.0.0",
    "x-clan-group" : "tickets",
    "x-module-group" : "tickets"
  },
  "paths" : {
    "/api/v1/tickets/{ticketId}/tags" : {
      "get" : {
        "tags" : [ "TicketTag" ],
        "summary" : "List tags in a ticket",
        "description" : "This API lists tags associated with a ticket.",
        "operationId" : "getTicketTags",
        "parameters" : [ {
          "$ref" : "#/components/parameters/ticketId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/getTagsByTicketResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.tickets.READ" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "policy" : "ReadAPI_Lenient_UserPolicy"
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "common",
          "apihash" : "e4b59f138a0fb620555461bffdc52b21",
          "module-group" : "views",
          "apimethod" : "com.zoho.support.restapi.TagsService.getTagsByTickets"
        }
      }
    },
    "/api/v1/tags/{id}" : {
      "put" : {
        "tags" : [ "TicketTag" ],
        "operationId" : "tagsRename",
        "parameters" : [ {
          "$ref" : "#/components/parameters/id"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/renameTag"
        },
        "responses" : {
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/invalidDataErrorResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/tagJson"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.tickets.UPDATE" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 300000,
                  "threshold" : 30,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "common",
          "apihash" : "ab9070db35a96b2ce5da0f9b2b1f4525",
          "module-group" : "views",
          "apimethod" : "com.zoho.support.restapi.TagsService.renameTag"
        }
      },
      "delete" : {
        "tags" : [ "TicketTag" ],
        "operationId" : "deleteTag",
        "parameters" : [ {
          "$ref" : "#/components/parameters/id"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "204" : {
            "$ref" : "../common/Common.json#/components/responses/emptyResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.tickets.DELETE" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 300000,
                  "threshold" : 30,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "common",
          "apihash" : "ab9070db35a96b2ce5da0f9b2b1f4525",
          "module-group" : "views",
          "apimethod" : "com.zoho.support.restapi.TagsService.deleteTag"
        }
      }
    },
    "/api/v1/tickets/{ticketId}/dissociateTag" : {
      "post" : {
        "tags" : [ "TicketTag" ],
        "summary" : "Dissociate Ticket Tags",
        "description" : "This API removes a single tag or multiple tags from a ticket.",
        "operationId" : "dissociateTicketTags",
        "parameters" : [ {
          "$ref" : "#/components/parameters/ticketId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/tagArray"
        },
        "responses" : {
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/invalidDataErrorResponse"
          },
          "200" : {
            "$ref" : "../common/Common.json#/components/responses/emptyResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.tickets.CREATE" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "policy" : "WriteAPI_Standard_UserPolicy,IscSignatureCalls_OrgPolicy"
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : {
              "system-auth" : "optional",
              "scoped-services" : [ "ZohoSupport" ]
            }
          },
          "clan-group" : "common",
          "apihash" : "5df4ffe2062f558c39c772931aa173cb",
          "module-group" : "views",
          "apimethod" : "com.zoho.support.restapi.TagsService.dissociateTags"
        }
      }
    },
    "/api/v1/recentTicketTags" : {
      "get" : {
        "tags" : [ "TicketTag" ],
        "summary" : "List recent tags",
        "description" : "This API lists the five most recent tags associated with tickets.",
        "operationId" : "getRecentTags",
        "parameters" : [ {
          "$ref" : "#/components/parameters/departmentId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/multipleUnprocessEntityResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/getTicketTagResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.tickets.READ" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 300000,
                  "threshold" : 30,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "common",
          "apihash" : "ab9070db35a96b2ce5da0f9b2b1f4525",
          "module-group" : "views",
          "apimethod" : "com.zoho.support.restapi.TagsService.getRecentTags"
        }
      }
    },
    "/api/v1/recentTicketTags/{tagId}" : {
      "post" : {
        "tags" : [ "TicketTag" ],
        "summary" : "Update recent tags",
        "description" : "This API adds a tag to the list of recently viewed tags. tag_id is a mandatory parameter in the API request.",
        "operationId" : "updateRecentTags",
        "parameters" : [ {
          "$ref" : "#/components/parameters/tagId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "../common/Common.json#/components/responses/emptyResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.tickets.CREATE" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 300000,
                  "threshold" : 50,
                  "hip" : false
                }, {
                  "duration" : 3600000,
                  "lock-period" : 900000,
                  "threshold" : 200,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "common",
          "apihash" : "ecf4af1e8c725568f2748ce4cfb91c04",
          "module-group" : "views",
          "apimethod" : "com.zoho.support.restapi.TagsService.updateRecentTags"
        }
      }
    },
    "/api/v1/tags/{tagId}/ticketsCount" : {
      "get" : {
        "tags" : [ "TicketTag" ],
        "summary" : "Get ticket count by tag",
        "description" : "This API returns how many tickets contain a particular tag.",
        "operationId" : "getTicketsCountByTag",
        "parameters" : [ {
          "$ref" : "#/components/parameters/tagId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/getCountResponse"
          },
          "404" : {
            "$ref" : "../common/Common.json#/components/responses/urlNotFoundErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.tickets.READ" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 180000,
                  "threshold" : 10,
                  "hip" : false
                }, {
                  "duration" : 3600000,
                  "lock-period" : 600000,
                  "threshold" : 100,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : {
              "iscscope" : [ "SupCrmAPI" ]
            }
          },
          "clan-group" : "common",
          "apihash" : "c559436b16ed6f5076a641ccff958ade",
          "module-group" : "views",
          "apimethod" : "com.zoho.support.restapi.RecordsCountService.getRequestCountByTag"
        }
      }
    },
    "/api/v1/tags/{currentTagId}/replace" : {
      "patch" : {
        "tags" : [ "TicketTag" ],
        "summary" : "Replace the specified tags",
        "description" : "This API replaces a tag to the specified tag. tag_id is a mandatory parameter in the API request.",
        "operationId" : "replaceTag",
        "parameters" : [ {
          "name" : "currentTagId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/replaceTag"
        },
        "responses" : {
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/invalidDataErrorResponse"
          },
          "204" : {
            "$ref" : "../common/Common.json#/components/responses/emptyResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.tickets.UPDATE" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 300000,
                  "threshold" : 30,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "common",
          "apihash" : "dee086098203948fb31d4345cd657503",
          "module-group" : "views",
          "apimethod" : "com.zoho.support.restapi.TagsService.replaceTag"
        }
      }
    },
    "/api/v1/ticketTags" : {
      "get" : {
        "tags" : [ "TicketTag" ],
        "summary" : "List tickets tags",
        "description" : "This API lists the ticket tags added in your help desk portal.�",
        "operationId" : "getTicketsTags",
        "parameters" : [ {
          "$ref" : "#/components/parameters/departmentId"
        }, {
          "$ref" : "#/components/parameters/limit"
        }, {
          "$ref" : "#/components/parameters/from"
        }, {
          "name" : "sortBy",
          "in" : "query",
          "description" : "Key that sorts tags by a specific attribute: createdTime or count. The default sorting order is descending.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string", "null" ],
            "description" : "Key that sorts tags by a specific attribute: createdTime or count. The default sorting order is descending.",
            "enum" : [ "createdTime", "count" ],
            "maxLength" : 100,
            "minLength" : 0
          }
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/multipleUnprocessEntityResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/getTicketTagResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.tickets.READ" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "policy" : "ReadAPI_Standard_UserPolicy,IscSignatureCalls_OrgPolicy"
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : {
              "system-auth" : "optional",
              "scoped-services" : [ "ZohoSupport" ]
            }
          },
          "clan-group" : "common",
          "apihash" : "f809afdfec4826748f7fc63f557ad621",
          "module-group" : "views",
          "apimethod" : "com.zoho.support.restapi.TagsService.getTicketTags"
        }
      }
    },
    "/api/v1/tickets/{ticketId}/associateTag" : {
      "post" : {
        "tags" : [ "TicketTag" ],
        "summary" : "Associate Ticket Tags",
        "description" : "This API adds a single tag or multiple tags to a ticket.",
        "operationId" : "associateTicketTags",
        "parameters" : [ {
          "$ref" : "#/components/parameters/ticketId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/associateTags_tagArray"
        },
        "responses" : {
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/invalidDataErrorResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/commonTagResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.tickets.CREATE" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "policy" : "WriteAPI_Standard_UserPolicy,IscSignatureCalls_OrgPolicy"
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : {
              "system-auth" : "optional",
              "scoped-services" : [ "ZohoSupport" ]
            }
          },
          "clan-group" : "common",
          "apihash" : "0549ecb3d2deec92afe81371bfb93386",
          "module-group" : "views",
          "apimethod" : "com.zoho.support.restapi.TagsService.associateTags"
        }
      }
    },
    "/api/v1/tags/search" : {
      "get" : {
        "tags" : [ "TicketTag" ],
        "summary" : "Search tags",
        "description" : "This API searches for tags added in your help desk portal.",
        "operationId" : "getTags",
        "parameters" : [ {
          "name" : "searchVal",
          "in" : "query",
          "description" : "Search keyword related to the tag.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string", "null" ],
            "description" : "Search keyword related to the tag.",
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "[a-z0-9\\_\\-\\+\\%\\P{InBasicLatin}\\s]+"
          }
        }, {
          "$ref" : "#/components/parameters/departmentId"
        }, {
          "$ref" : "#/components/parameters/limit"
        }, {
          "$ref" : "#/components/parameters/from"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/multipleUnprocessEntityResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/commonTagResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.tickets.READ" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "policy" : "ReadAPI_Standard_UserPolicy,IscSignatureCalls_OrgPolicy"
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : {
              "system-auth" : "optional",
              "scoped-services" : [ "ZohoSupport" ]
            }
          },
          "clan-group" : "tickets",
          "apihash" : "b35327ed6215f4dc76fd8c4defff1f48",
          "module-group" : "tickets",
          "apimethod" : "com.zoho.support.restapi.TagsService.getTags"
        }
      }
    },
    "/api/v1/tags/{tagId}/tickets" : {
      "get" : {
        "tags" : [ "TicketTag" ],
        "summary" : "List tickets by tag",
        "description" : "This API lists tickets containing the tag specified.",
        "operationId" : "getTicketsByTag",
        "parameters" : [ {
          "name" : "include",
          "in" : "query",
          "description" : "Additional information related to the tickets. Values allowed are: @contacts@, @products@, @departments@, @team@, @isRead@ and @assignee@. You can pass multiple values by separating them with commas.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string", "null" ],
            "description" : "Additional information related to the tickets. Values allowed are: @contacts@, @products@, @departments@, @team@, @isRead@ and @assignee@. You can pass multiple values by separating them with commas.",
            "enum" : [ "contacts", "isRead", "products", "assignee" ],
            "maxLength" : 100,
            "minLength" : 0,
            "x-custom-parameters-attributes" : {
              "split" : ",",
              "entity" : "Include"
            }
          }
        }, {
          "$ref" : "#/components/parameters/limit"
        }, {
          "$ref" : "#/components/parameters/from"
        }, {
          "name" : "sortBy",
          "in" : "query",
          "description" : "Key that sorts the tickets by a specific attribute: @dueDate@, @recentThread@, @createdTime@, or @ticketNumber@. The default sorting order is ascending. A - prefix denotes a descending order of sorting.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string", "null" ],
            "description" : "Key that sorts the tickets by a specific attribute: @dueDate@, @recentThread@, @createdTime@, or @ticketNumber@. The default sorting order is ascending. A - prefix denotes a descending order of sorting.",
            "enum" : [ "createdTime", "modifiedTime" ],
            "maxLength" : 100,
            "minLength" : 0
          }
        }, {
          "$ref" : "#/components/parameters/tagId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "204" : {
            "$ref" : "../common/Common.json#/components/responses/emptyResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/ticketListViewArray"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.tickets.READ" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 300000,
                  "threshold" : 20,
                  "hip" : false
                }, {
                  "duration" : 3600000,
                  "lock-period" : 900000,
                  "threshold" : 100,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "tickets",
          "apihash" : "9c958f702ded6f1e67e2b007e056a309",
          "module-group" : "tickets",
          "apimethod" : "com.zoho.support.restapi.RequestService.getTicketsForTag"
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "tagJson" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "name" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "^(?!^null$)[a-zA-Z0-9\\_\\.\\-\\+\\%\\P{InBasicLatin}\\s]{3,}$"
          },
          "tagType" : {
            "type" : [ "string", "null" ],
            "enum" : [ "SYSTEM", "MANUAL" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "id" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        },
        "required" : [ "id", "name", "tagType" ]
      },
      "data" : {
        "type" : [ "null", "array" ],
        "items" : {
          "$ref" : "#/components/schemas/tagJson"
        }
      },
      "getTicketTagJson" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "ticketCount" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int32",
            "pattern" : "([0-9]+)"
          },
          "name" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "^(?!^null$)[a-zA-Z0-9\\_\\.\\-\\+\\%\\P{InBasicLatin}\\s]{3,}$"
          },
          "tagType" : {
            "type" : [ "string", "null" ],
            "enum" : [ "SYSTEM", "MANUAL", null ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "id" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        },
        "required" : [ "id", "name", "tagType", "ticketCount" ]
      },
      "getTicketTagData" : {
        "type" : [ "null", "array" ],
        "items" : {
          "$ref" : "#/components/schemas/getTicketTagJson"
        }
      },
      "ticketData" : {
        "type" : [ "null", "array" ],
        "items" : {
          "$ref" : "./Ticket.json#/components/schemas/ticketTags"
        }
      }
    },
    "responses" : {
      "getTagsByTicketResponse" : {
        "description" : "getTagsByTicketResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "tags" : {
                  "$ref" : "#/components/schemas/data"
                }
              },
              "required" : [ "tags" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "tags" : [ {
                    "name" : "sample",
                    "tagType" : "MANUAL",
                    "id" : 123234324
                  }, {
                    "name" : "sample",
                    "tagType" : "MANUAL",
                    "id" : 123234324
                  } ]
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "getTicketTagResponse" : {
        "description" : "getTicketTagResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "data" : {
                  "$ref" : "#/components/schemas/getTicketTagData"
                }
              },
              "required" : [ "data" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "data" : [ {
                    "ticketCount" : "10",
                    "name" : "sample",
                    "tagType" : "MANUAL",
                    "id" : "12312312312"
                  }, {
                    "ticketCount" : "0",
                    "name" : "sample",
                    "tagType" : "MANUAL",
                    "id" : "12312312312"
                  } ]
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "getCountResponse" : {
        "description" : "getCountResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "count" : {
                  "type" : [ "string", "null", "integer" ],
                  "format" : "int64",
                  "pattern" : "([0-9]+)"
                }
              },
              "required" : [ "count" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "count" : "10"
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "commonTagResponse" : {
        "description" : "commonTagResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "data" : {
                  "$ref" : "#/components/schemas/data"
                }
              },
              "required" : [ "data" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "data" : [ {
                    "name" : "sample",
                    "tagType" : "MANUAL",
                    "id" : 123234324
                  }, {
                    "name" : "sample",
                    "tagType" : "SYSTEM",
                    "id" : 123234324
                  } ]
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "tagJson" : {
        "description" : "tagJson template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "name" : {
                  "type" : [ "string", "null" ],
                  "description" : "Names of the tag",
                  "maxLength" : 100,
                  "minLength" : 3,
                  "pattern" : "^(?!^null$)[a-zA-Z0-9\\_\\.\\-\\+\\%\\P{InBasicLatin}\\s]{3,}$"
                },
                "tagType" : {
                  "type" : [ "string", "null" ],
                  "enum" : [ "SYSTEM", "MANUAL" ],
                  "maxLength" : 100,
                  "minLength" : 0
                },
                "id" : {
                  "type" : [ "string", "null", "integer" ],
                  "format" : "int64",
                  "pattern" : "([0-9]+)"
                }
              },
              "required" : [ "id", "name", "tagType" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : null
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "ticketListViewArray" : {
        "description" : "ticketListViewArray template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "allOf" : [ {
                "type" : "object",
                "properties" : {
                  "data" : {
                    "type" : "array",
                    "items" : {
                      "type" : "object",
                      "properties" : {
                        "product" : {
                          "type" : [ "null", "object" ],
                          "additionalProperties" : false,
                          "maxProperties" : 2,
                          "minProperties" : 2,
                          "properties" : {
                            "id" : {
                              "type" : [ "string", "null", "integer" ],
                              "format" : "int64",
                              "pattern" : "([0-9]+)"
                            },
                            "productName" : {
                              "type" : [ "string", "null" ],
                              "maxLength" : 200,
                              "minLength" : 0
                            }
                          },
                          "required" : [ "id", "productName" ]
                        },
                        "contact" : {
                          "type" : [ "null", "object" ],
                          "additionalProperties" : false,
                          "maxProperties" : 8,
                          "minProperties" : 8,
                          "properties" : {
                            "lastName" : {
                              "type" : [ "string", "null" ],
                              "maxLength" : 200,
                              "minLength" : 0
                            },
                            "firstName" : {
                              "type" : [ "string", "null" ],
                              "maxLength" : 40,
                              "minLength" : 0
                            },
                            "phone" : {
                              "type" : [ "string", "null" ],
                              "maxLength" : 50,
                              "minLength" : 0,
                              "pattern" : "[0-9a-zA-Z_\\+\\-\\.\\(\\)\\$@\\?\\,\\:\\'\\/\\!\\P{InBasicLatin}\\s]+"
                            },
                            "mobile" : {
                              "type" : [ "string", "null" ],
                              "maxLength" : 50,
                              "minLength" : 0,
                              "pattern" : "[0-9a-zA-Z_\\+\\-\\.\\(\\)\\$@\\?\\,\\:\\'\\/\\!\\P{InBasicLatin}\\s]+"
                            },
                            "id" : {
                              "type" : [ "string", "null", "integer" ],
                              "format" : "int64",
                              "pattern" : "([0-9]+)"
                            },
                            "type" : {
                              "type" : [ "string", "null" ],
                              "x-dynamic-enum" : true
                            },
                            "email" : {
                              "type" : [ "string", "null" ],
                              "maxLength" : 255,
                              "minLength" : 0,
                              "pattern" : "^[a-zA-Z0-9\\_]([a-zA-Z0-9\\_\\+\\-\\.\\'\\&\\~]*)@(?=.{4,256}$)(([a-zA-Z0-9]+)(([\\-\\_]*[a-zA-Z0-9])*)[\\.])+[a-zA-Z]{2,22}$"
                            },
                            "account" : {
                              "type" : [ "null", "object" ],
                              "additionalProperties" : false,
                              "maxProperties" : 3,
                              "minProperties" : 3,
                              "properties" : {
                                "website" : {
                                  "type" : [ "string", "null" ],
                                  "maxLength" : 120,
                                  "minLength" : 0
                                },
                                "accountName" : {
                                  "type" : [ "string", "null" ],
                                  "maxLength" : 200,
                                  "minLength" : 0
                                },
                                "id" : {
                                  "type" : [ "string", "null", "integer" ],
                                  "format" : "int64",
                                  "pattern" : "([0-9]+)"
                                }
                              },
                              "required" : [ "accountName", "id", "website" ]
                            }
                          },
                          "required" : [ "account", "email", "firstName", "id", "lastName", "mobile", "phone", "type" ]
                        },
                        "isRead" : {
                          "type" : [ "boolean", "null" ]
                        },
                        "assignee" : {
                          "type" : [ "null", "object" ],
                          "additionalProperties" : false,
                          "maxProperties" : 5,
                          "minProperties" : 5,
                          "properties" : {
                            "firstName" : {
                              "type" : [ "string", "null" ],
                              "maxLength" : 50,
                              "minLength" : 0
                            },
                            "photoURL" : {
                              "type" : [ "string", "null" ],
                              "maxLength" : 200,
                              "minLength" : 0,
                              "pattern" : "(^(ht|f)tp(s?)\\://[-.\\w]*(/?)([a-zA-Z0-9\\-\\.\\?\\,\\:\\'/\\\\+=&amp;%\\$#_@]*)?$)"
                            },
                            "lastName" : {
                              "type" : [ "string", "null" ],
                              "maxLength" : 50,
                              "minLength" : 0
                            },
                            "id" : {
                              "type" : [ "string", "null", "integer" ],
                              "format" : "int64",
                              "pattern" : "([0-9]+)"
                            },
                            "email" : {
                              "type" : [ "string", "null" ],
                              "maxLength" : 100,
                              "minLength" : 0,
                              "pattern" : "^[a-zA-Z0-9\\_]([a-zA-Z0-9\\_\\+\\-\\.\\'&]*)@(?=.{4,256}$)(([a-zA-Z0-9]+)(([\\-\\_]*[a-zA-Z0-9])*)[\\.])+[a-zA-Z]{2,22}$"
                            }
                          },
                          "required" : [ "email", "firstName", "id", "lastName", "photoURL" ]
                        },
                        "team" : {
                          "type" : [ "null", "object" ],
                          "additionalProperties" : false,
                          "maxProperties" : 3,
                          "minProperties" : 3,
                          "properties" : {
                            "name" : {
                              "type" : [ "string", "null" ],
                              "maxLength" : 50,
                              "minLength" : 1,
                              "pattern" : "([0-9a-zA-Z_\\-\\.\\$@\\?\\,\\:\\'\\/\\!\\P{InBasicLatin}\\s])+"
                            },
                            "id" : {
                              "type" : [ "string", "null", "integer" ],
                              "format" : "int64",
                              "pattern" : "([0-9]+)"
                            },
                            "logoUrl" : {
                              "type" : [ "string", "null" ],
                              "maxLength" : 200,
                              "minLength" : 0,
                              "pattern" : "(^(ht|f)tp(s?)\\://[-.\\w]*(/?)([a-zA-Z0-9\\-\\.\\?\\,\\:\\'/\\\\+=&amp;%\\$#_@]*)?$)"
                            }
                          },
                          "required" : [ "id", "logoUrl", "name" ]
                        },
                        "department" : {
                          "type" : [ "null", "object" ],
                          "additionalProperties" : false,
                          "maxProperties" : 2,
                          "minProperties" : 2,
                          "properties" : {
                            "name" : {
                              "type" : [ "string", "null" ],
                              "maxLength" : 200,
                              "minLength" : 0,
                              "pattern" : "([0-9a-zA-Z_\\-\\.\\$@\\?\\,\\:\\'\\/\\!\\P{InBasicLatin}\\s])+"
                            },
                            "id" : {
                              "type" : [ "string", "null", "integer" ],
                              "format" : "int64",
                              "pattern" : "([0-9]+)"
                            }
                          },
                          "required" : [ "id", "name" ]
                        }
                      }
                    }
                  }
                }
              }, {
                "type" : [ "null", "object" ],
                "additionalProperties" : false,
                "properties" : {
                  "data" : {
                    "$ref" : "#/components/schemas/ticketData"
                  }
                },
                "required" : [ "data" ]
              } ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "data" : [ {
                    "ticketNumber" : "101",
                    "statusType" : "Open",
                    "subject" : "Real Time analysis Requirement",
                    "dueDate" : 1466525776000,
                    "departmentId" : "1892000000006907",
                    "channel" : "Email",
                    "isRead" : true,
                    "language" : "English",
                    "closedTime" : null,
                    "contact" : {
                      "lastName" : "Carol",
                      "firstName" : "Lucas",
                      "phone" : "1 888 900 9646",
                      "mobile" : "8838109870",
                      "id" : "1892000000042032",
                      "isSpam" : false,
                      "type" : "paid",
                      "email" : "carol@zylker.com",
                      "account" : {
                        "website" : "www.desk.com",
                        "accountName" : "desk Account",
                        "id" : "1892000000975382"
                      }
                    },
                    "createdTime" : 1383564067000,
                    "id" : "1892000000042034",
                    "department" : {
                      "name" : "dasdasdasd",
                      "id" : "1892000000006907"
                    },
                    "email" : "carol@zylker.com",
                    "customerResponseTime" : 1383564067912,
                    "productId" : null,
                    "contactId" : "1892000000042032",
                    "threadCount" : "121",
                    "team" : {
                      "name" : "kjsdfjks",
                      "id" : "8920000000069071",
                      "logoUrl" : "https://desk.zoho.com/api/v1/teams/8920000000069071/logo?orgId=11278831"
                    },
                    "priority" : "High",
                    "assigneeId" : "1892000000056007",
                    "commentCount" : "1",
                    "accountId" : "189200000005345",
                    "phone" : null,
                    "webUrl" : "https://desk.zoho.com/support/zylker/ShowHomePage.do#Cases/dv/d126330fb061247d9ebddaeb9d93ba74750b0284bc703b38",
                    "teamId" : "8920000000069071",
                    "assignee" : {
                      "firstName" : "dasca",
                      "lastName" : "vins",
                      "photoURL" : "https://desk.zoho.com/api/v1/agents/1892000000056007/photo?orgId=298902",
                      "id" : "1892000000056007",
                      "email" : "jack@zylker.com"
                    },
                    "isSpam" : false,
                    "status" : "Open"
                  }, {
                    "ticketNumber" : "169",
                    "statusType" : "Open",
                    "subject" : "Hi. There is a sudden delay in the processing of the orders. Check this with high priority",
                    "dueDate" : null,
                    "departmentId" : "1892000000006907",
                    "channel" : "Facebook",
                    "isRead" : true,
                    "closedTime" : null,
                    "contact" : {
                      "lastName" : "Richard",
                      "firstName" : "Lucas",
                      "phone" : "1 888 900 9646",
                      "mobile" : "8838109870",
                      "id" : "1892000000093203",
                      "isSpam" : false,
                      "type" : "paid",
                      "email" : "richard@zylker.com",
                      "account" : {
                        "website" : "www.desk.com",
                        "accountName" : "desk Account",
                        "id" : "1892000000975382"
                      }
                    },
                    "createdTime" : 1394098493000,
                    "id" : "1892000000093205",
                    "department" : {
                      "name" : "dasdasdasd",
                      "id" : "1892000000006907"
                    },
                    "email" : "carol@zylker.com",
                    "customerResponseTime" : 1394524289618,
                    "productId" : null,
                    "contactId" : "1892000000093203",
                    "threadCount" : "43",
                    "team" : {
                      "name" : "kjsdfjks",
                      "id" : "8920000000069071",
                      "logoUrl" : "https://desk.zoho.com/api/v1/teams/8920000000069071/logo?orgId=11278831"
                    },
                    "priority" : null,
                    "assigneeId" : "1892000000042001",
                    "commentCount" : "0",
                    "phone" : null,
                    "webUrl" : "https://desk.zoho.com/support/zylker/ShowHomePage.do#Cases/dv/d126330fb061247d9ebddaeb9d93ba74750b0284bc703b38",
                    "teamId" : "8920000000069071",
                    "assignee" : {
                      "firstName" : "dasca",
                      "lastName" : "vins",
                      "photoURL" : "https://desk.zoho.com/api/v1/agents/1892000000042001/photo?orgId=298902",
                      "id" : "1892000000042001",
                      "email" : "jack@zylker.com"
                    },
                    "isSpam" : false,
                    "status" : "Open"
                  } ]
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      }
    },
    "parameters" : {
      "tagId" : {
        "name" : "tagId",
        "in" : "path",
        "required" : true,
        "style" : "simple",
        "explode" : false,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int64",
          "pattern" : "([0-9]+)"
        }
      },
      "departmentId" : {
        "name" : "departmentId",
        "in" : "query",
        "description" : "ID of the department from which the tags must be fetched",
        "required" : true,
        "style" : "form",
        "explode" : true,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int64",
          "description" : "ID of the department from which the tags must be fetched",
          "pattern" : "([0-9]+)",
          "x-custom-parameters-attributes" : {
            "entity" : "Departments"
          }
        }
      },
      "limit" : {
        "name" : "limit",
        "in" : "query",
        "description" : "Number of tags to fetch",
        "required" : false,
        "style" : "form",
        "explode" : true,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int32",
          "description" : "Number of tags to fetch",
          "pattern" : "([0-9]+)"
        }
      },
      "from" : {
        "name" : "from",
        "in" : "query",
        "description" : "Index number, starting from which the tags must be fetched",
        "required" : false,
        "style" : "form",
        "explode" : true,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int32",
          "description" : "Index number, starting from which the tags must be fetched",
          "pattern" : "([0-9]+)"
        }
      },
      "id" : {
        "name" : "id",
        "in" : "path",
        "required" : true,
        "style" : "simple",
        "explode" : false,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int64",
          "pattern" : "([0-9]+)"
        }
      },
      "ticketId" : {
        "name" : "ticketId",
        "in" : "path",
        "required" : true,
        "style" : "simple",
        "explode" : false,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int64",
          "pattern" : "([0-9]+)"
        }
      }
    },
    "requestBodies" : {
      "tagArray" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "tags" : {
                  "type" : [ "null", "array" ],
                  "items" : {
                    "type" : [ "string", "null" ],
                    "maxLength" : 100,
                    "minLength" : 0,
                    "pattern" : "^(?!^null$)[a-zA-Z0-9\\_\\.\\-\\+\\%\\P{InBasicLatin}\\s]{3,}$",
                    "x-custom-parameters-attributes" : [ ]
                  },
                  "uniqueItems" : false
                }
              },
              "required" : [ "tags" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "tags" : [ "sample", "ticket", "tag" ]
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      },
      "replaceTag" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "id" : {
                  "type" : [ "string", "null", "integer" ],
                  "format" : "int64",
                  "description" : "Tag ID of the Replacing Tag",
                  "pattern" : "([0-9]+)"
                }
              },
              "required" : [ "id" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "id" : "12312312312"
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      },
      "associateTags_tagArray" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "tags" : {
                  "type" : [ "null", "array" ],
                  "items" : {
                    "type" : [ "string", "null" ],
                    "maxLength" : 100,
                    "minLength" : 0,
                    "pattern" : "^(?!^null$)[a-zA-Z0-9\\_\\.\\-\\+\\%\\P{InBasicLatin}\\s]{3,}$",
                    "x-custom-parameters-attributes" : [ ]
                  },
                  "uniqueItems" : false
                }
              },
              "required" : [ "tags" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "tags" : [ "sample", "ticket", "tag" ]
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      },
      "renameTag" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "name" : {
                  "type" : [ "string", "null" ],
                  "description" : "Names of the tag",
                  "maxLength" : 100,
                  "minLength" : 0,
                  "pattern" : "^(?!^null$)[a-zA-Z0-9\\_\\.\\-\\+\\%\\P{InBasicLatin}\\s]{3,}$"
                }
              },
              "required" : [ "name" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : null
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      }
    },
    "securitySchemes" : {
      "cookie-auth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/cookie-auth"
      },
      "org-oauth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/org-oauth"
      },
      "iam-oauth2-schema" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/iam-oauth2-schema"
      }
    }
  },
  "x-entity" : "TicketTag"
}